[env:lilygo-t-display-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200

lib_deps =
    lovyan03/LovyanGFX
    https://github.com/tzapu/WiFiManager.git
    HomeSpan/HomeSpan
    bblanchon/ArduinoJson

build_flags = 
    -DARDUINO_ARCH_ESP32
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
